### ISSUE TITLE
Challenge Implementation Questions

### ISSUE THREAD

**Issue by akontovasilakos** [DanoBroz/cat-lover#1]
Hey, good effort on this challenge! We really appreciate that you took the time to submit it.

I would appreciate it a lot if you could take some time and answer a couple of questions regarding your implementation.
- I see that you have used the `e.stopPropagation()` function call to a number of click handlers. Could you please explain why is that and if they are necessary on all the cases? As a bonus question: In which case would someone need to use the `stopPropagation()` function call?
-  In a number of components the props aren't strictly defined, and there is a tendency to use the rest operator for the unknown props. What is the thinking behind that and how it helped you in that particular implementation?
- Do you have any experience with testing? How would you approach (in a high level) testing in this assignment?

Thanks in advance!

**Comment by DanoBroz** [comment]
Hi,

thank you for your time and code review, if there’s any piece of code you’d write differently, feel free to point it out, I’m always open to new improvements.

To answer your questions:

I’m using nested components that are within (parent) component with the usage of other click event handlers. Well since you pointed it out, there’s one situation when it doesn’t solve anything (probably kept playing with the component and forgot about it) in the BreedCard component. So to answer the followup question - stopPropagation - is used for prevention of event bubbling, that means stop triggering parents event handler.
In my use cases I use rest operators to pass all (the rest of) component props - since I’m only extending the html native component. So I can use all the native props on extended component everywhere if needed and strictly define and use only those Inside the component itself.

Hopefully I’ve answered your questions understandably :-). If there’s something you’d want me to explain more in depth do not hesitate to contact me.

Have a nice rest of the day.

Kind regard
Daniel Brož

**Comment by akontovasilakos** [comment]
Hey, 

Thanks a lot for taking the time to reply.
I would appreciate it if you could also answer the last question regarding testing, if you have the time.
No pressure on that, we just like to have an idea as testing is part of our day to day work.

Thanks a lot,
Alexandros

**Comment by DanoBroz** [comment]
Hi,

always happy to share my point of view, when requested.

I’m not sure if I understand it correctly in this particular case. Rest props helps me here to extend my component with element props I didn’t strictly define and be more flexible in terms of usability. With Typescript I can define rules of the component and ensure it’s used correctly, ex. prevent bugs with passing href property on div element or other data that don’t comply with defined rules.

Let me know, if I was able to answer your question or completely ruined your expectations (and day).

Kind regard,
Daniel

**Comment by akontovasilakos** [comment]
Hey again, 

Sorry if I wasn't clear enough, but the last question I was referring was: 
`Do you have any experience with testing? How would you approach (in a high level) testing in this assignment?`

I got your point about the rest props in your previous answer.

Thank you,
Alexandros

**Comment by DanoBroz** [comment]
Hi,

sorry, I didn’t receive the updated version of questions into mail manager, that I’m replying from (screenshot in attachments).

Currently I don’t have any experience with high-level testing. Since every company I worked for have its own testers.

Nevertheless, I’d love to get your opinion on testing tools and your preference.

Kind regards
Daniel Brož

￼

**Comment by akontovasilakos** [comment]
Hey!
No worries, I got the confusion!
Thanks for your reply. I would suggest to have a look at this one: https://testing-library.com/

Thanks again for all your effort and your replies!
